data:
  path: "data/raw/dataset.csv"
  split:
    train_size: 0.8
    random_state: 42

preprocessing:
  target: "price"
  features: ["area", "bedrooms", "bathrooms", "stories", "parking"]
  numeric:
    imputation_strategy: "mean"
  categorical:
    imputation_strategy: "most_frequent"

models:
  regresion_logistica:
    solver: ["liblinear", "saga"]
    C: [0.1, 1.0, 10]
    max_iter: [100, 500, 1000]
  random_forest:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, 15]
    min_samples_split: [2, 5, 10]

hyperparameter_search:
  n_iter: 10
  scoring: "accuracy"
  n_jobs: -1
  cv_folds: 5
